# Generated by Django 3.2.5 on 2024-10-21 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_auto_20211109_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='fleet.bus')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='fleet.driver')),
            ],
        ),
        migrations.AddIndex(
            model_name='busshift',
            index=models.Index(fields=['bus', 'start_time', 'end_time'], name='fleet_bussh_bus_id_ae89cd_idx'),
        ),
        migrations.AddIndex(
            model_name='busshift',
            index=models.Index(fields=['driver', 'start_time', 'end_time'], name='fleet_bussh_driver__a1f75c_idx'),
        ),
        migrations.AddConstraint(
            model_name='busshift',
            constraint=models.UniqueConstraint(fields=('bus', 'start_time', 'end_time'), name='unique_bus_shift'),
        ),
        migrations.AddConstraint(
            model_name='busshift',
            constraint=models.UniqueConstraint(fields=('driver', 'start_time', 'end_time'), name='unique_driver_shift'),
        ),
    ]
