# Generated by Django 3.2.5 on 2024-10-21 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
        ('fleet', '0003_auto_20241021_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_order', models.PositiveIntegerField(verbose_name='Order of the stop in the bus route')),
                ('bus_shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus_stops', to='fleet.busshift')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_stops', to='geography.place')),
            ],
            options={
                'ordering': ['stop_order'],
                'unique_together': {('bus_shift', 'stop_order')},
            },
        ),
    ]
